### ISSUE TITLE
Angular Services unit tests failing always

### ISSUE THREAD

**Issue by arunkutty** [arunkutty/ExpenseVoucher-WebClient#1]
Unit tests generated by Angular Services yeoman generator is failing every time. The error message indicates that the Service object is not being loaded. 
This is the error trace: 
_PhantomJS 2.1.1 (Mac OS X 0.0.0) Service: dummyService should do something FAILED
	/Users/arun/developer/WebstormProjects/ExpenseVouchersClient/bower_components/angular/angular.js:4527:53
	forEach@/Users/arun/developer/WebstormProjects/ExpenseVouchersClient/bower_components/angular/angular.js:321:24
	loadModules@/Users/arun/developer/WebstormProjects/ExpenseVouchersClient/bower_components/angular/angular.js:4487:12
	createInjector@/Users/arun/developer/WebstormProjects/ExpenseVouchersClient/bower_components/angular/angular.js:4409:30
	workFn@/Users/arun/developer/WebstormProjects/ExpenseVouchersClient/bower_components/angular-mocks/angular-mocks.js:2799:60
	**TypeError: undefined is not an object (evaluating 'dummyService.dummyVar') in /Users/arun/developer/WebstormProjects/ExpenseVouchersClient/test/spec/services/dummyservice.js (line 15)
	/Users/arun/developer/WebstormProjects/ExpenseVouchersClient/test/spec/services/dummyservice.js:15:24**_

**Comment by arunkutty** [comment]
@floydpink, I've been trying to learn unit testing of Angular applications and have been trying that out in this project. I spent lot of time on this issue but have been unsuccessful so far. Can you take a look and find if I missed something obvious? In order to isolate the problem, I've written a simple dummy service but the problem happens with that as well.

**Comment by arunkutty** [comment]
:smile_cat: Spent more time on this one that I can admit. Good part is that I learnt some basics of how Angular works.

**Comment by floydpink** [comment]
> Good part is that...

Only that matters. :smile:
